---
title: "Overview"
subtitle: "Core 2: File types, workflow tips and other tools"
---

This week we will consider File types, workflow tips and other tools. The independent study reiterates the value of RStudio projects and shows you how you create them with **`usethis`**. You will also learn how to recognise and write cool 😎 code, not 😩 ugly code and code algorithmically. In the workshop we will examine some common biological data formats and discover some awesome short cuts to help you write cool 😎 code. You will also get a brief introduction to the command line and Google Colab.

### Learning objectives

The successful student will be able to:

-   explain why RStudio are useful/essential and be able to use the **`usethis`** package 
-   write cool 😎 code not 😩 ugly code
-   explain the value of code which expresses the structure of the problem/solution.
-   describe some common file types for biological data
-   use some useful shortcuts to help write cool 😎 code
-   know what the command line is and how to use it for simple tasks
-   use Google colab to run code
-   recognise some of the differences between R and Python

### Instructions

1.  [Prepare](study_before_workshop.qmd) 20 mins reading on RStudio Projects revisited, formatting code and coding algorithmically


2.  [Workshop](workshop.qmd)

    i.  💬 Types of biological data files

    ii. 🪄 Workflow tips and shortcuts

    iii. 💻 The command line
    
    iv.  💻 Google colab
    
    v.  💻 Python

3.  [Consolidate](study_after_workshop.qmd)

    i.  💻 not sure yet :)


