project:
  type: website
  output-dir: _site

date: last-modified
date-format: D MMMM, YYYY

website:
  title: "Data Analysis for Group Project"
  google-analytics: "G-TVF95J593T"
  
  page-footer:
    left: "Rand E (2024). Data Analysis for Group Project. <https://3mmarand.github.io/BIO00088H-data/>."
    right:
      - icon: twitter
        href: https://twitter.com/er_13
        aria-label: Twitter
      - icon: github
        href: https://github.com/3mmaRand/BIO00088H-data
        aria-label: BIO00088H-data GitHub
  navbar:
    background: light
    twitter-card: true
    site-url: https://3mmarand.github.io/BIO00088H-data/
    repo-url: https://github.com/3mmaRand/BIO00088H-data
    issue-url: https://github.com/3mmaRand/BIO00088H-data/issues/new/choose
    repo-actions: [edit, issue]
    page-navigation: true
    search: true
    left:
      - text: "Welcome!"
        file: index.qmd
      - text: "Core Supporting Info"
        file:  core/core.qmd
      - text: "Transcriptomics"
        file:  transcriptomics/transcriptomics.qmd
      - text: "Image Analysis"
        file:  images/images.qmd
      - text: "Structure Analysis"
        file:  structures/structures.qmd
    tools:
      - icon: twitter
        href: https://twitter.com/er_13
        text: Emma's Twitter
      - icon: github
        href: https://github.com/3mmaRand/BIO00088H-data
        text: BIO00088H-data GitHub

  sidebar:
    - title: "Core"
      style: "floating"
      contents: 
          - href: core/core.qmd
          - section: "Week 2: Supporting Information 1"
            contents: 
             - href: core/week-2/overview.qmd
               text: About  
             - href: core/week-2/study_before_workshop.qmd
               text: Prepare! 
             - href: core/week-2/workshop.qmd
               text: Workshop
             - href: core/week-2/study_after_workshop.qmd
               text: Consolidate!  
          - section: "Week 6: Supporting Information 2"
            contents: 
             - href: core/week-6/overview.qmd
               text: About  
             - href: core/week-6/study_before_workshop.qmd
               text: Prepare! 
             - href: core/week-6/workshop.qmd
               text: Workshop
             - href: core/week-6/study_after_workshop.qmd
               text: Consolidate!  
    - title: "Omics"
      style: "floating"
      contents: 
          - href: transcriptomics/transcriptomics.qmd
          - section: "Week 3: Hello data!"
            contents: 
             - href: transcriptomics/week-3/overview.qmd
               text: About  
             - href: transcriptomics/week-3/study_before_workshop.qmd
               text: Prepare! 
             - href: transcriptomics/week-3/workshop.qmd
               text: Workshop
             - href: transcriptomics/week-3/study_after_workshop.qmd
               text: Consolidate!  
          - section: "Week 4: Statistical Analysis"
            contents: 
             - href: transcriptomics/week-4/overview.qmd
               text: About  
             - href: transcriptomics/week-4/study_before_workshop.qmd
               text: Prepare! 
             - href: transcriptomics/week-4/workshop.qmd
               text: Workshop
             - href: transcriptomics/week-4/study_after_workshop.qmd
               text: Consolidate!  
          - section: "Week 5: Visualising and Interpreting"
            contents: 
             - href: transcriptomics/week-5/overview.qmd
               text: About  
             - href: transcriptomics/week-5/study_before_workshop.qmd
               text: Prepare! 
             - href: transcriptomics/week-5/workshop.qmd
               text: Workshop
             - href: transcriptomics/week-5/study_after_workshop.qmd
               text: Consolidate!  
          - section: "Semester 2: Extras"
            contents: 
             - href: transcriptomics/semester-2/stem_cell_variant.qmd
               text: Additional 🐭 stem cell labels  
          - section: "Kelly's Project"
            contents: 
             - href: transcriptomics/kelly/workshop.qmd
               text: Workshop
    - title: "Images"
      style: "floating"
      contents: 
          - href: images/images.qmd
          - text: Extra help
    - title: "Structures"
      style: "floating"
      contents: 
          - href: structures/structures.qmd
          - text: Extra help

execute:
  echo: true
  warning: false
  output: true
  error: true
  collapse: true


format:
  html:
    css: styles.css
    link-external-newwindow: true
    link-external-filter: '^(?:http:|https:)\/\/3mmarand\.github\.io\/BIO00088H-data'
    theme:
      light: [cosmo, styles.scss]
    code-copy: true
    code-link: true
    code-overflow: wrap
    code-line-numbers: false
    grid:
      sidebar-width: 250px
      body-width: 900px
      margin-width: 300px
    
    author-meta: Emma Rand

bibliography: references.bib


editor: source



