---
title: "Data Analysis for the Group Research Project"
toc: true
toc-location: right
---

# Overview

You are *either*

-   an integrated masters student doing BIO00088H Group Research Project *or*
-   an MSc Bioinformatics student doing BIO00070M Research, Professional and Team Skills

Integrated masters students doing 88H will be doing one of these projects:

The project types are:

| Title                                                                         | Director        | Data analysis strand            |
|--------------------------------------|------------|----------------------|
| Identifying transcriptional targets of FGF signalling in Xenopus embryos.     | Betsy Pownall   | Transcriptomics, Emma Rand      |
| Investigating the differentiation of stem cells in healthy bone marrow        | Jillian Barlow  | Transcriptomics, Emma Rand      |
| Investigating  pathways involved in the Nickel detoxification in Willow       | Liz Rylott      | Transcriptomics, Emma Rand      |
| Investigating differential RNA expression through the Leishmania lifecycle    | Pegine Walrad   | Transcriptomics, Emma Rand      |
| Identifying novel proteins regulating synaptophagy                            | Richard Maguire | Image analysis, Richard Bingham |
| Defining pathological cascades in dopaminergic neurons in a Parkinson's model | Sean Sweeney    | Image analysis, Richard Bingham |
| Discovery proteins for biotech applications: new classes of antibody mimetics | Michael Plevin  | Structure Analysis, Jon Agirre  |

Data Analysis compromises five workshops covering computational skills needed in your project. MSc Bioinformatics students do the Core workshops and the transcriptomics workshops as part of BIO00070M. The data analysis workshops are:

| Week | Data Strand                                                                                            |
|---------------|---------------------------------------------------------|
| 2    | Core 1 Supporting Information - reproducibility, project-oriented workflow, naming things,             |
| 3    | Strand specific 1                                                                                      |
| 4    | Strand specific 2                                                                                      |
| 5    | Strand specific 3                                                                                      |
| 6    | Core 2 Supporting Information - documenting, curating, cool code, handy shortcuts, non-coded processes |
|      |                                                                                                        |

## Module Learning Outcome linked to this content

Students who successfully complete this module will be able to

-   use appropriate computational techniques to reproducibly process, analyse and visualise data and generate scientific reports based on project work.

## What is this site for?

All material is on the VLE so why is this site useful? This site collects everything together in a searchable way. The search icon is on the top right.

## Please cite as

Rand E (2024). Data Analysis for Group Project. https://3mmarand.github.io/BIO00088H-data/.
