---
title: "Transcriptomics Data Analysis for Group Project"
toc: true
toc-location: right
---

# Content

## Transcriptomics 1: 👋 Hello data!

This week you will meet your data. There are three datasets, one for
each project in this strand. The independent study will concisely cover
how each of these three data sets were generated and how they have been
processed before being given to you. It will also give an overview of
the analysis we will carry out over three workshops. In the workshop,
you will learn what steps to take to get a good understanding of
transciptomic data before you consider any statistical analysis. This is
an often overlooked, but very valuable and informative, part of any data
pipeline. It will give you the understanding of the data and R data
structures that you will need to code and trouble-shoot code. It will
also allow you to spot failed or problematic samples and will inform
your decisions on quality control. At the end of this workshop and the
following independent study you will have performed quality control by
filtering out uninformative genes and samples, and saved this filtered
data for use in the next workshop. You will also have a script that you
can use to repeat this process on other datasets.

## Transcriptomics 2: Statistical Analysis

This week we cover differential expression analysis on your quality
controlled data. The independent study will allow you to check you have
what you should have following the [Transcriptomics 1: Hello Data
workshop](week-3/workshop.html) and [Consolidation
study](week-3/study_after_workshop.html). It then summarises the
concepts and methods used to carry out differential expression analysis
in workshop. In the workshop, you will perform the differential
expression and learn how to computationally annotate your genes with
more information from the databases. This will include the Gene Ontology
(GO) terms that describe the biological processes, molecular functions
and cellular components that the gene is involved in. At the end of this
workshop and the following independent study you will have files
containing the genes which are differentially expressed, along with the
statistical information, summary information and annotation. You will be
able to consider which genes you want to investigates with your Project
director and have what you need for the next workshop. You will also
have a script that you can use to repeat this process on other datasets.

## Transcriptomics 3: Visualising and Interpreting

This week you will learn some how to do some common data visualisations
for transcriptomic data. You will conduct and present a Principal
Component Analysis (PCA) and a Volcano plot. The independent study will
allow you to check you have what you should have following the
[Transcriptomics 2: Statistical Analysis workshop](week-4/workshop.html)
and [Consolidation study](week-4/study_after_workshop.html). At the end
of this workshop and the following independent study you will have at
least two figures suitable for including in your report, along with an
understanding of the results you can report on. You will also have a
script that you can use to repeat this process on other datasets.

References
