---
title: "Omics Data Analysis for Group Project"
toc: true
toc-location: right
---

# Content

## Omics 1: 👋 Hello data!

This week you will meet your data. The independent study will concisely cover how these data were generated and how they have been processed before being given to you. There will also be an overview of the analysis we will carry out over three workshops.
In the workshop, you will learn what steps to take to get a good understanding of ’omics data before you consider any statistical analysis. This is an often overlooked, but very valuable and informative, part of any data pipeline. It gives you the deep understanding of the data structures and values that you will need to code and trouble-shoot code, allows you to spot failed or problematic samples and informs your decisions on quality control.



## Omics 2: Statistical Analysis

This week we cover differential expression analysis on raw counts or log normalised values. The independent study will allow you to check you have what you should have following the [Omics 1: Hello Data workshop](week-3/workshop.html) and [Consolidation study](week-3/study_after_workshop.html). It will also summarise the concepts and methods we will use in the workshop. In the workshop, you will learn how to perform differential expression analysis on raw counts using **`DESeq2`** [@DESeq2] or on logged normalised expression values using **`scran`** [@scran] or both.

## Omics 3: Visualising and Interpreting

before

-   recap what we have
-   PCA
-   volcano plot described
-   GO terms
-   


workshop

-   PCA
-   volcano plot
-   annotating with go terms

after

-   document what you have done
-   repeat on another comparison

References