---
title: "Overview"
subtitle: "Transcriptomics 1: 👋 Hello data!"
toc: true
toc-location: right
---

This week you will meet your data. The independent study will concisely cover how these data were generated and how they have been processed before being given to you. There will also be an overview of the analysis we will carry out over three workshops.
In the workshop, you will learn what steps to take to get a good understanding of ’omics data before you consider any statistical analysis. This is an often overlooked, but very valuable and informative, part of any data pipeline. It gives you the deep understanding of the data structures and values that you will need to code and trouble-shoot code, allows you to spot failed or problematic samples and informs your decisions on quality control.

We suggest you sit together with your group in the workshop.

### Learning objectives

The successful student will be able to:

-   explore transcriptomics data to find the number of rows and columns and know how these correspond to samples and variables
-   explore the distribution of expression measures across whole data sets, across variables and across samples by summarising and plotting
-   explain what distributions are expected and interpret the distributions they have
-   explain on what basis we might filter out variables or samples
-   import, explore and filter transcriptomics data reproducibly so they can understand and reuse their code in the future

### Instructions

1.  [Prepare](study_before_workshop.qmd)
    
    i.   📖 Read how the data were generated and how they have been processed so far 


2.  [Workshop](workshop.qmd)

    i.   💻 Set up a Project

    ii.  💻 Import data

    iii. 💻 Explore the distribution of values across samples/cells and across genes/species
    
    iv.  💻 Look after future you!

3.  [Consolidate](study_after_workshop.qmd)

    i.  💻 Use the work you completed in the workshop as a template to apply to a new case.


