---
title: "Independent Study to prepare for workshop"
subtitle: "Omics 2: Statistical Analysis"
author: "Emma Rand"
format: 
  revealjs:
    footer: "🔗 [About Omics 2: Statistical Analysis](https://3mmarand.github.io/BIO00088H-data/omics/week-4/overview.html)"
    slide-number: true
    chalkboard: true
    code-link: true
    code-line-numbers: false
bibliography: ../../references.bib
editor: 
  markdown: 
    wrap: 72
---

## Overview

::: incremental

-   Check where you are.

-   Basis of comparisons
    -   normalisation
    -   statistical model
    -   Multiple correction

-   Methods vary
    -   DESeq2
    -   edgeR
    -   limma
    -   scran
:::

# Where should you be?

## 🐸 Frogs

After the Omics 1 Workshop, Look after future you and the Independent Study to consolidate, you should have:

-   An RStudio Project called `frogs-88H` which contains

    -   Raw data (S14, S20 and S30)
    -   Processed data (s20_filtered.csv, s20_summary_gene.csv, s20_summary_gene_filtered.csv, s20_summary_samp.csv, s30_filtered.csv, s30_summary_gene.csv, s30_summary_gene_filtered.csv, s30_summary_samp.csv)
    -   Two scripts called cont-fgf-s30.R and cont-fgf-s20.R

These should be organised into folders. Code should well commented and easy to read.

Note: you may have done S14 instead of S20.


## 🐭 Mice

After the Omics 1 Workshop, Look after future you and the Independent Study to consolidate, you should have:

-   An RStudio Project called `mice-88H` which contains

    -   Raw data (hspc, prog, lthsc)
    -   Processed data (hspc_summary_gene.csv, hspc_summary_samp.csv, prog_summary_gene.csv, prog_summary_samp.csv)
    -   One script called hspc-prog.R

These should be organised into folders. Code should well commented and easy to read.

## 🍂 xxxx


Either of the other examples.

##

further explore with PCA

what is pca


## DESeq2

the Negative Binomial is a good approximation for data where the
mean < variance i.e., more clumped

Goal of DE is to identify and correct for sources of variation that are not
due to treatments

explain normalisation # https://hbctraining.github.io/DGE_workshop_salmon_online/lessons/02_DGE_count_normalization.html
#  this is a good account of normalisation methods

To normalize for sequencing depth and RNA composition,

DESeq2 uses the median of ratios method. This happens automatically
when we do the DE. models the normalization inside the Generalized Linear Model

data must be raw counts

## DESeq2

DESeq2 needs 
-   a metadata file which contain information about the samples and the treatments
-   a matrix of the counts
-   a design formula which describes the model to be fitted. it must use the columns in the metadat file.



##

```{r}
#| echo: false
library(tidyverse)
## Import metadata that maps the sample names to treatments
meta <- read_table("meta/frog_meta_data.txt")
knitr::kable(meta)

```


## DESeq2


differential expression results

log2 foldhcange - explain why log2
a tests statistic,  

baseMean, log2FoldChange, lfcSE, stat, pvalue and padj, and also includes metadata columns of variable information. The lfcSE gives the standard error of the log2FoldChange. For the Wald test, stat is the Wald statistic:


a p-value and a padj

explain the adjusted p value.




## References
