---
title: "Overview"
subtitle: "Omics 3: Visualising and Interpreting"
toc: true
toc-location: right
---

This week we cover how to visualise and interpret the results of your differential expression analysis. The independent study will allow you to check you have what you should have following the [Omics 2: Statistical Analysis workshop](../week-4/workshop.html) and [Consolidation study](../week-4/study_after_workshop.html). It will also summarise the the methods and plots we will go through in the workshop. In the workshop, we will learn how to merge gene information into our results, conduct a Principle Component Analysis (PCA) and plot the results as well as how to create a nicely formatted Volcano plot and heatmap.  

We suggest you sit together with your group in the workshop.

### Learning objectives

The successful student will be able to:

-   verify they have the required RStudio Project set up and the data and code files from the previous Workshop and Consolidation study
-   explain where gene information came from and add it to their results
-   perform a PCA and understand how to interpret them
-   create a heatmap and understand how to interpret them
-   create a volcano plot and understand how to interpret them
  

### Instructions

1.  [Prepare](study_before_workshop.qmd)

    i.  📖 Read what you should have so far and about concepts in PCA, volcano plots and heatmaps.

2.  [Workshop](workshop.qmd)

    i.  💻 Add gene information to the results of DE

    ii. 💻 Perform and plot a PCA

    iii. 💻 Visualise results with a heatmap
    
    iv. 💻 Visualise all the results with a volcano plot

    iv. Look after future you!

3.  [Consolidate](study_after_workshop.qmd)

    i.  💻 Use the work you completed in the workshop as a template to apply to a new case.

### References
