---
title: "Overview"
subtitle: "Core 3: Research Compendia and Reproducible Reporting"
toc: true
toc-location: right
---

This week we will cover the “Research compendium” and reproducible reporting which are part of the assessment. Research Compendium that is a documented collection of all the digital parts of the research project including data (or access to data), code and outputs. The Compendium might be a single Quarto/RStudio Project, or it might be a folder including an Quarto/RStudio Project and some additional materials including the description of unscripted processing. The collection is organised and documented in such a way that reproducing all the results is straightforward for another individual. We will also cover reproducible reporting which means using literate programming to weave together code and text together in a single document. Quarto is a multi-language literate programming tool (very like R Markdown).

### Learning objectives

The successful student will be able to:

-   explain what a research compendium is and describe its components
-   relate the content and concepts in Core 1 and Core 2 to the
    research compendium
-   Create a quarto document and:
    -   appreciate the role of the YAML header 
    -   format text as bold, italics, headings etc
    -   add citations and a bibliography
    -   create automatically numbered figures and tables with cross references in text
    -   set default code chunk behaviour and those for individual chunks 
    -   use inline code to report results
    -   insert special characters and mathematical expressions with LaTeX


### Instructions

1.  [Prepare](study_before_workshop.qmd)


2.  [Workshop](workshop.qmd)


3.  Consolidate by working on your project and research compendium

