---
title: "Independent Study to prepare for workshop"
subtitle: "Core 3 Research Compendia and Reproducible Reporting"
author: "Emma Rand"
format: 
  revealjs:
    footer: "🔗 [About Core 3 Research Compendia and Reproducible Reporting](https://3mmarand.github.io/BIO00088H-data/core/week-11/overview.html)"
    slide-number: true
    chalkboard: true
    code-link: true
    code-line-numbers: false
bibliography: ../../references.bib
editor: 
  markdown: 
    wrap: 72
---

## Module assessment

This module is assessed by:

-   Oral presentation 30%

-   Project Report and Research Compendium 70% of which

    -   50% report
    -   20% compendium

These slides are a guide to Research compendium.

## What is a Research Compendium?

**Overview of assessment**

::: {style="font-size: 65%;"}
*Stage 3 Integrated Masters students are expected to submit a Research
Compendium that is a documented collection of all the digital parts of
the research project including data (or access to data), code and
outputs. The Compendium might be a single Quarto/RStudio Project, or it
might be a folder including an Quarto/RStudio Project and some
additional materials including the description of unscripted processing.
The collection is organised and documented in such a way that
reproducing all the results is straightforward for another individual.*

*Students will be assessed on the technical complexity, completeness and
organisation of their compendium and the completeness, reproducibility
and clarity of their documentation at the project and the code/process
level. Marking will focus on the reproducibility of the results and the
clarity of the decision making processes rather than the interpretation
of the results which is covered in the report. There is no word or size
limit for any part of the compendium but its contents should be concise
and minimal. Extraneous text, code or files will be penalised.*
:::

## What is a Research Compendium?

**Overview of assessment**

::: {style="font-size: 65%;"}
*Stage 3 Integrated Masters students are expected to submit a Research
Compendium that is a* **documented collection of all the digital parts
of the research project including data (or access to data), code and
outputs.** *The Compendium might be a single Quarto/RStudio Project, or
it might be a folder including an Quarto/RStudio Project and some
additional materials including the description of unscripted
processing.* **The collection is organised and documented in such a way
that reproducing all the results is straightforward for another
individual.**

*Students will be assessed on the* **technical complexity, completeness
and organisation of their compendium and the completeness,
reproducibility and clarity of their documentation at the project and
the code/process level.** *Marking will focus on the reproducibility of
the results and the clarity of the decision making processes rather than
the interpretation of the results which is covered in the report. There
is no word or size limit for any part of the compendium but its contents
should be concise and minimal. Extraneous text, code or files will be
penalised.*
:::

## What is a Research Compendium?

::: {style="font-size: 80%;"}
::: incremental
-   Zipped folder containing all data, code and text associated with a
    research project organised and documented clearly. Any unscripted
    processing should be described.

-   Everything needed to understand what the project is and reproduce
    the results, and no more. The compendium should not be a dumping
    ground for data files and scripts. It needs to be curated. You may
    generate files that are not needed to reproduce your work and these
    should be removed.

-   Your compendium might be a single Quarto/RStudio Project, or it
    might be folder including an RStudio Project and some additional
    materials including the description of unscripted processing.

-   Ideally uses literate programming to create submitted report
:::
:::

## Use guidelines from Core 1 and 2

-   follow the guidance in [Core
    1](https://3mmarand.github.io/BIO00088H-data/core/week-1/overview.html)
    on organisation, naming things and documentation

-   follow the guidance in [Core
    2](https://3mmarand.github.io/BIO00088H-data/core/week-2/overview.html)
    on well-formatted code, consistency, modularisation and
    documentation

## Project level documentation

::: incremental
-   as concise as possible, bullet points are good

-   primarily in the README file but some details may be in scripts

-   title, concise description of the work, author exam number, date,
    overview of compendium contents

-   all the software information including versions

-   instructions needed to reproduce the work, order of workflow,
    settings/parameter values for software
:::

## Project level documentation - cont

::: incremental
-   description, format and provenance of the data

-   style conventions used in the code,

-   any other information needed to understand the project and reproduce
    the results
:::

## Script level documentation

Shorthand for documentation at the script and/or code chunk level and/or
process level where unscripted processing is used.

::: incremental
-   overview of the script/chunk/process and its purpose

-   code comments
:::

## What is a Research Compendium?

::: incremental
-   A research compendium is something you develop throughout your
    research project. It is not something you create at the end.

-   You update and reorganise as you go.

-   When you plan your research include the planning of recording,
    organising, and documenting your data and its analysis.

-   Think ahead to how and where you will be recording your data and how
    you will be analysing.
:::

## Further Reading

-   [The Turing Way](https://the-turing-way.netlify.app/index.html#)
    [@community2022]

-   Packaging Data Analytical Work Reproducibly Using R (and Friends)
    [@marwick2018]

-   Ten simple rules for writing and sharing computational analyses in
    Jupyter Notebooks [@rule2019]

-   Ten Simple rules for [@sandve2013]

## References
