---
title: "Workshop"
subtitle: "Research Compendia and Reproducible Reporting"
author: "Emma Rand"
toc: true
toc-depth: 4
toc-location: right
execute:
  echo: true
  include: true
  error: true
bibliography: ../../references.bib
editor: 
  markdown: 
    wrap: 72
---

```{r}
#| include: false
library(tidyverse)
```

# Introduction

## Literate Programming

-   Literate programming is a way of writing code and text together in a single document

-   The document is then processed to produce a report

-   [Quarto](https://quarto.org/) (recommended) or [R Markdown](https://rmarkdown.rstudio.com/index.html) 


## Session overview

In this workshop we will go through an example quarto document. You will learn:

-   what the YAML header is 
-   formatting (bold, italics, headings)
-   to control default and individual chunk options 
-   how to add citations
-   figures and tables with cross referencing and automatic numbering
-   how to use inline coding to report results
-   how to insert special characters and equations

# Exercise

🎬 The example RStudio project containing this code here: [chaffinch](https://github.com/3mmaRand/chaffinch). You can download the project as a zip file from there but there is some code that will do that automatically for you. Since this is an RStudio Project, do not run the code from inside a project. You may want to navigate to a particular directory or edit the `destdir`:

```r
usethis::use_course(url = "3mmaRand/chaffinch", destdir = ".")

```
You can agree to deleting the zip. You should find RStudio restarts and you have a new project called chaffinch-xxxxxx. The xxxxxx is a commit reference - you do not need to worry about that, it is just a way to tell you which version of the repo you downloaded. You can now run the code in the project.

🎬 Make an outline of your compendium. This could be a sketch on paper or slide or from the mindmap software you usually use. Or it could be a skeleton of folders and files on your computer.

🎬 Make a start on a quarto doc. 



You're finished!

# 🥳 Well Done! 🎉



# Independent study following the workshop

[Consolidate](study_after_workshop.qmd)

# The Code file

These contain all the code needed in the workshop even where it is not visible on the webpage.

The [workshop.qmd](workshop.qmd) file is the file I use to compile the practical. Qmd stands for Quarto markdown. It allows code and ordinary text to be interleaved to produce well-formatted reports including webpages. Right-click on the link and choose Save-As to download. You will be able to open the Qmd file in RStudio. Alternatively, [View in Browser](https://github.com/3mmaRand/BIO00088H-data/core/week-11/workshop.qmd). Coding and thinking answers are marked with `#---CODING ANSWER---` and `#---THINKING ANSWER---`

Pages made with R [@R-core], Quarto [@allaire2022], `knitr` [@knitr], `kableExtra` [@kableExtra]

# References
