---
title: "Overview"
subtitle: "Core: Supporting Information 1"
toc: true
toc-location: right
---

This week you will revise some essential concepts for scientific computing: file system organisation, file types, working directories and paths. The workshop will cover a rationale for working reproducibly, project oriented workflow, naming things and documenting your work. 


### Learning objectives

The successful student will be able to:

-   explain the organisation of files and directories in a file systems including root, home and working directories
-   explain absolute and relative file paths
-   explain why working reproducibly is important
-   know how to use a project-oriented workflow to organise work
-   be able to give files human- and machine-readable names
-   write cool 😎 code not 😩 ugly code
-   explain the value of code which expresses the structure of the problem/solution.
-   use some useful shortcuts to help write cool 😎 code

### Instructions

1.  [Prepare](study_before_workshop.qmd)

    i.  📖 Read Understanding file systems
    ii.  📖 Read Workflow in RStudio

2.  [Workshop](workshop.qmd)


3.  [Consolidate](study_after_workshop.qmd)

