---
title: "Workshop"
subtitle: "File types, workflow tips and other tools"
author: "Emma Rand"
toc: true
toc-depth: 4
toc-location: right
execute:
  echo: true
  include: true
  error: true
bibliography: ../../references.bib
editor: 
  markdown: 
    wrap: 72
engine: knitr
---

# Introduction

## Session overview

In this workshop you will



# File types


Types of Data files. 
-   Sequences data 
-   Image data 
-  Structure data PDB/mmCIF  www.pdb.org

Similarities and differences

# Workflow tips

🎬 Make a new RStudio project (use the workflow from in the independent
study


-   multiple cursors

-   open a file

-   the command palette, 

-   segmenting code

-   to correct indentation CONTROL+i

-   to reformat code CONTROL+SHIFT+A Not perfect but corrects spacing, indentation, multiple commands on lines and assignment with `=`

-   to comment and uncomment lines CONTROL+SHIFT+C

-   Tools | Global options | Code | Display | Show margin

-   Tools | Global options | Code | Diagnostic | Provide R style diagnostics

-   [GitHub Copilot in RStudio, it’s finally here!](https://colorado.posit.co/rsc/rstudio-copilot/#/TitleSlide)







restart R

# Other tools

## The command line

The command line - or shell - is a text interface for your computer.
It's a program that takes in commands, which it passes on to the
computer's operating system to run.


-   Windows PowerShell is a command-line in windows. It uses bash-like commands unlike the Command Prompt which uses dos commands (a sort of windows only language). You can open is by going to Start | Windows PowerShell or by searching for it in the search bar.

- Terminal is the command line in Mac OS X. You can open it by going to Applications | Utilities | Terminal or by searching for it in the Spotlight search bar.

-   git bash. I used the bash shell that comes with [Git](https://git-scm.com/)

### RStudio terminal

The RStudio terminal is a convenient interface to the shell without
leaving RStudio. It is useful for running commands that are not
available in R. For example, you can use it to run other programs like
fasqc, git, ftp, ssh

### Using a command line

We are going to learn some commands navigating your folders from the command line


```{bash}

```


```{bash}
ls
```


```{bash}
ls -l
```

```{bash}
ls -F
```

# Google Colab

# Python

## Differences between R and python


## Quarto note books

zotero

🎬

You're finished!

# 🥳 Well Done! 🎉

# Independent study following the workshop

[Consolidate](study_after_workshop.qmd)

# The Code file

These contain all the code needed in the workshop even where it is not
visible on the webpage.

The [workshop.qmd](workshop.qmd) file is the file I use to compile the
practical. Qmd stands for Quarto markdown. It allows code and ordinary
text to be interleaved to produce well-formatted reports including
webpages. Right-click on the link and choose Save-As to download. You
will be able to open the Qmd file in RStudio. Alternatively, [View in
Browser](https://github.com/3mmaRand/). Coding and thinking answers are
marked with `#---CODING ANSWER---` and `#---THINKING ANSWER---`

Pages made with R [@R-core], Quarto [@allaire2022], `knitr` [@knitr],
`kableExtra` [@kableExtra]

# References
